<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class NewProductsJuly extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('products')->insert([
            ['artcode'      => '68407723',
            'artdesc'       => 'LIFEBUOY BAR TOTAL10 ST',
            'primcs'        => '0',
            'secondcs'      => '2057.14',
            'price'         => '0',
            'artshrtdesc'   => '',
            'unitconv2'     => '144',
            'stat'          => 'Active',
            'site'          => '4048',
            'uom2'          => 'CS',
            'uom3'          => '',
            'volumecs'      => '18489.24',
            'volumecsl'     => '0',
            'volumepc'      => '103.73',
            'volumepcl'     => '0',
            'widthcs'       => '230',
            'widthpc'       => '55',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '0',
            'unitconv3'     => '0',
            'merchcat'      => 'F150',
            'brand'         => 'LIFEBUOY',
            'category'      => 'SKIN CLEANSING',
            'subcat'        => '',
            'division'      => 'BEAUTY & PERSONAL CARE',
            'assortnum'     => 'PH_HPCFR',
            'listmod'       => '10000000432',
            'assortstat'    => '',
            'grosswghtpc'   => '87',
            'netwghtpc'     => '75',
            'grosswghtcs'   => '12.7',
            'netwghtcs'     => '10800',
            'lengthpc'      => '82',
            'heightpc'      => '23',
            'lengthcs'      => '308',
            'heightcs'      => '261',
            'photo'         => '',
            'inventory'     => '0'],
            ['artcode'      => '68407725',
            'artdesc'       => 'LIFEBUOY BAR LEMONFRESH',
            'primcs'        => '0',
            'secondcs'      => '2057.14',
            'price'         => '0',
            'artshrtdesc'   => '',
            'unitconv2'     => '144',
            'stat'          => 'Active',
            'site'          => '4B48',
            'uom2'          => 'CS',
            'uom3'          => '',
            'volumecs'      => '18489.24',
            'volumecsl'     => '0',
            'volumepc'      => '103.73',
            'volumepcl'     => '0',
            'widthcs'       => '230',
            'widthpc'       => '55',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '0',
            'unitconv3'     => '0',
            'merchcat'      => 'F150',
            'brand'         => 'LIFEBUOY',
            'category'      => 'SKIN CLEANSING',
            'subcat'        => '',
            'division'      => 'BEAUTY & PERSONAL CARE',
            'assortnum'     => 'PH_HPCFR',
            'listmod'       => '10000000432',
            'assortstat'    => '',
            'grosswghtpc'   => '87',
            'netwghtpc'     => '75',
            'grosswghtcs'   => '12.7',
            'netwghtcs'     => '10800',
            'lengthpc'      => '82',
            'heightpc'      => '23',
            'lengthcs'      => '308',
            'heightcs'      => '261',
            'photo'         => '',
            'inventory'     => '0'],
            ['artcode'      => '67876306',
            'artdesc'       => 'FISSAN SOOTHING RELIEF BABY PWDR',
            'primcs'        => '0',
            'secondcs'      => '2573.57',
            'price'         => '0',
            'artshrtdesc'   => '',
            'unitconv2'     => '48',
            'stat'          => 'Active',
            'site'          => '4048',
            'uom2'          => 'CS',
            'uom3'          => '',
            'volumecs'      => '15312',
            'volumecsl'     => '0',
            'volumepc'      => '280.83',
            'volumepcl'     => '0',
            'widthcs'       => '290',
            'widthpc'       => '37',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '0',
            'unitconv3'     => '0',
            'merchcat'      => 'F150',
            'brand'         => 'FISSAN',
            'category'      => 'SKIN CARE',
            'subcat'        => '',
            'division'      => 'BEAUTY & PERSONAL CARE',
            'assortnum'     => 'PH_HPCFR',
            'listmod'       => '10000000432',
            'assortstat'    => '',
            'grosswghtpc'   => '69',
            'netwghtpc'     => '50',
            'grosswghtcs'   => '3.82',
            'netwghtcs'     => '2400',
            'lengthpc'      => '69',
            'heightpc'      => '110',
            'lengthcs'      => '440',
            'heightcs'      => '120',
            'photo'         => '',
            'inventory'     => '0'],
            ['artcode'      => '67876303',
            'artdesc'       => 'FISSAN SOOTHING RELIEF BABY PWDR',
            'primcs'        => '0',
            'secondcs'      => '1938.21',
            'price'         => '0',
            'artshrtdesc'   => '',
            'unitconv2'     => '72',
            'stat'          => 'Active',
            'site'          => '4048',
            'uom2'          => 'CS',
            'uom3'          => '',
            'volumecs'      => '17556',
            'volumecsl'     => '0',
            'volumepc'      => '456.225',
            'volumepcl'     => '0',
            'widthcs'       => '220',
            'widthpc'       => '77',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '0',
            'unitconv3'     => '0',
            'merchcat'      => 'F150',
            'brand'         => 'FISSAN',
            'category'      => 'SKIN CARE',
            'subcat'        => '',
            'division'      => 'BEAUTY & PERSONAL CARE',
            'assortnum'     => 'PH_HPCFR',
            'listmod'       => '10000000432',
            'assortstat'    => '',
            'grosswghtpc'   => '43',
            'netwghtpc'     => '25',
            'grosswghtcs'   => '3.46',
            'netwghtcs'     => '1800',
            'lengthpc'      => '75',
            'heightpc'      => '79',
            'lengthcs'      => '420',
            'heightcs'      => '190',
            'photo'         => '',
            'inventory'     => '0'],
            ['artcode'      => '68204048',
            'artdesc'       => 'SURF PWDR CHRY BLSM',
            'primcs'        => '0',
            'secondcs'      => '761.92',
            'price'         => '0',
            'artshrtdesc'   => '',
            'unitconv2'     => '3',
            'stat'          => 'Active',
            'site'          => '4048',
            'uom2'          => 'CS',
            'uom3'          => '',
            'volumecs'      => '14400',
            'volumecsl'     => '0',
            'volumepc'      => '5292',
            'volumepcl'     => '0',
            'widthcs'       => '320',
            'widthpc'       => '70',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '0',
            'unitconv3'     => '0',
            'merchcat'      => 'F070',
            'brand'         => 'SURF',
            'category'      => 'FABRIC SOLUTIONS CATEGORY',
            'subcat'        => '',
            'division'      => 'HOME CARE',
            'assortnum'     => 'PH_HPCFR',
            'listmod'       => '10000002128',
            'assortstat'    => '',
            'grosswghtpc'   => '4447',
            'netwghtpc'     => '4400',
            'grosswghtcs'   => '13.52',
            'netwghtcs'     => '13200',
            'lengthpc'      => '210',
            'heightpc'      => '360',
            'lengthcs'      => '500',
            'heightcs'      => '90',
            'photo'         => '',
            'inventory'     => '0']
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
