<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddMerisantItems extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('products')->insert([
            ['artcode'      => 'MRST0001',
            'artdesc'       => 'Equal Classic 1000X1g',
            'primcs'        => '1390.00',
            'secondcs'      => '1390.00',
            'price'         => '1390.00',
            'artshrtdesc'   => '',
            'unitconv2'     => '1',
            'stat'          => 'Active',
            'site'          => 'MRST',
            'uom2'          => 'PC',
            'uom3'          => '',
            'volumecs'      => '',
            'volumecsl'     => '',
            'volumepc'      => '',
            'volumepcl'     => '',
            'widthcs'       => '',
            'widthpc'       => '',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '',
            'unitconv3'     => '',
            'merchcat'      => '',
            'brand'         => 'Equal Classic',
            'category'      => 'MERISANT',
            'subcat'        => 'MERISANT',
            'division'      => '',
            'assortnum'     => '',
            'listmod'       => '',
            'assortstat'    => '',
            'grosswghtpc'   => '',
            'netwghtpc'     => '',
            'grosswghtcs'   => '',
            'netwghtcs'     => '',
            'lengthpc'      => '',
            'heightpc'      => '',
            'lengthcs'      => '',
            'heightcs'      => '',
            'photo'         => '',
            'inventory'     => '0'],
            ['artcode'      => 'MRST0002',
            'artdesc'       => 'Equal Gold 750X0.8g',
            'primcs'        => '1100.00',
            'secondcs'      => '1100.00',
            'price'         => '1100.00',
            'artshrtdesc'   => '',
            'unitconv2'     => '1',
            'stat'          => 'Active',
            'site'          => 'MRST',
            'uom2'          => 'PC',
            'uom3'          => '',
            'volumecs'      => '',
            'volumecsl'     => '',
            'volumepc'      => '',
            'volumepcl'     => '',
            'widthcs'       => '',
            'widthpc'       => '',
            'bum'           => '',
            'uom1'          => '',
            'unitconv1'     => '',
            'unitconv3'     => '',
            'merchcat'      => '',
            'brand'         => 'Equal Gold',
            'category'      => 'MERISANT',
            'subcat'        => 'MERISANT',
            'division'      => '',
            'assortnum'     => '',
            'listmod'       => '',
            'assortstat'    => '',
            'grosswghtpc'   => '',
            'netwghtpc'     => '',
            'grosswghtcs'   => '',
            'netwghtcs'     => '',
            'lengthpc'      => '',
            'heightpc'      => '',
            'lengthcs'      => '',
            'heightcs'      => '',
            'photo'         => '',
            'inventory'     => '0'],
            ['artcode'      => 'MRST0004',
            'artdesc'       => 'Equal Gold (Sugarly) 12X400g',
            'primcs'        => '399.00',
            'secondcs'      => '399.00',
            'price'         => '399.00',
            'artshrtdesc'   => '',
            'unitconv2'     => '1',
            'stat'          => 'Active',
            'site'          => 'MRST',
            'uom2'          => 'PC',
            'uom3'          => '',
            'volumecs'      => '',
            'volumecsl'     => '',
            'volumepc'      => '',
            'volumepcl'     => '',
            'widthcs'       => '',
            'widthpc'       => '',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '',
            'unitconv3'     => '',
            'merchcat'      => '',
            'brand'         => 'Equal Gold',
            'category'      => 'MERISANT',
            'subcat'        => 'MERISANT',
            'division'      => '',
            'assortnum'     => '',
            'listmod'       => '',
            'assortstat'    => '',
            'grosswghtpc'   => '',
            'netwghtpc'     => '',
            'grosswghtcs'   => '',
            'netwghtcs'     => '',
            'lengthpc'      => '',
            'heightpc'      => '',
            'lengthcs'      => '',
            'heightcs'      => '',
            'photo'         => '',
            'inventory'     => '0'],
            ['artcode'      => 'MRST0005',
            'artdesc'       => 'Stevia Naturals 12X100X2g',
            'primcs'        => '358.00',
            'secondcs'      => '358.00',
            'price'         => '358.00',
            'artshrtdesc'   => '',
            'unitconv2'     => '1',
            'stat'          => 'Active',
            'site'          => 'MRST',
            'uom2'          => 'PC',
            'uom3'          => '',
            'volumecs'      => '',
            'volumecsl'     => '',
            'volumepc'      => '',
            'volumepcl'     => '',
            'widthcs'       => '',
            'widthpc'       => '',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '',
            'unitconv3'     => '',
            'merchcat'      => '',
            'brand'         => 'Stevia Naturals',
            'category'      => 'MERISANT',
            'subcat'        => 'MERISANT',
            'division'      => '',
            'assortnum'     => '',
            'listmod'       => '',
            'assortstat'    => '',
            'grosswghtpc'   => '',
            'netwghtpc'     => '',
            'grosswghtcs'   => '',
            'netwghtcs'     => '',
            'lengthpc'      => '',
            'heightpc'      => '',
            'lengthcs'      => '',
            'heightcs'      => '',
            'photo'         => '',
            'inventory'     => '0'],
            ['artcode'      => 'MRST0006',
            'artdesc'       => 'Purevia 12X100X0.8g',
            'primcs'        => '300.00',
            'secondcs'      => '300.00',
            'price'         => '300.00',
            'artshrtdesc'   => '',
            'unitconv2'     => '1',
            'stat'          => 'Active',
            'site'          => 'MRST',
            'uom2'          => 'PC',
            'uom3'          => '',
            'volumecs'      => '',
            'volumecsl'     => '',
            'volumepc'      => '',
            'volumepcl'     => '',
            'widthcs'       => '',
            'widthpc'       => '',
            'bum'           => 'PC',
            'uom1'          => '',
            'unitconv1'     => '',
            'unitconv3'     => '',
            'merchcat'      => '',
            'brand'         => 'Purevia',
            'category'      => 'MERISANT',
            'subcat'        => 'MERISANT',
            'division'      => '',
            'assortnum'     => '',
            'listmod'       => '',
            'assortstat'    => '',
            'grosswghtpc'   => '',
            'netwghtpc'     => '',
            'grosswghtcs'   => '',
            'netwghtcs'     => '',
            'lengthpc'      => '',
            'heightpc'      => '',
            'lengthcs'      => '',
            'heightcs'      => '',
            'photo'         => '',
            'inventory'     => '0']
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
